import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
function load(file,imports={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:n=>imports[n],Error,URL,URLSearchParams,Response,AbortSignal,AbortController,Set,Date,process:{env:{}},...globals});return exports;}
const entry={id:42,version:0,title:'Delivery',note:null,kind:'DELIVERY',priority:'NORMAL',date:'2026-10-10',endDate:'2026-10-10',time:'09:00',endTime:null,assignee:null,completed:false,createdAt:'2026-10-10T00:00:00Z',updatedAt:'2026-10-10T00:00:00Z'};
const api=load('lib/calendar-api.ts');
test('numeric IDs, versions, nullable inputs, editable-only payloads',()=>{const e=api.decodeEntry(entry);assert.equal(e.id,42);assert.equal(e.note,'');assert.equal(e.endTime,'');const post=api.editableEntry(e);assert.equal(post.note,null);assert.equal(post.id,undefined);assert.equal(post.version,undefined);assert.equal(post.createdAt,undefined);assert.equal(api.editableEntry({...e,version:1},true).version,1);for(const bad of [{...entry,id:'42'},{...entry,version:null},{...entry,priority:'LOW'},{...entry,date:'2026-02-30'}])assert.throws(()=>api.decodeEntry(bad));});
test('CRUD requests, authoritative returned version, conflict, 204, malformed list',async()=>{let request;let reply=entry;let status=201;const client=load('lib/calendar-api.ts',{}, {fetch:async(url,options)=>{request={url,options};return new Response(status===204?null:JSON.stringify(reply),{status});}});const e=api.decodeEntry(entry);assert.equal((await client.calendarRequest('',{method:'POST',body:JSON.stringify(api.editableEntry(e))})).id,42);assert.equal(request.options.method,'POST');reply={...entry,version:1,completed:true};status=200;assert.equal((await client.calendarRequest('/42',{method:'PUT',body:JSON.stringify(api.editableEntry({...e,completed:true},true))})).version,1);reply={...entry,version:2,completed:false};assert.equal((await client.calendarRequest('/42',{method:'PUT'})).completed,false);status=409;reply={message:'stale version'};await assert.rejects(client.calendarRequest('/42',{method:'PUT'}),e=>e.status===409&&e.message.includes('stale version'));status=204;assert.equal(await client.calendarRequest('/42?version=2',{method:'DELETE'}),null);assert.equal(request.url,'/api/calendar/entries/42?version=2');status=200;reply={content:[]};await assert.rejects(client.calendarRequest('?from=2026-10-01&to=2026-10-31'),/Expected an array/);});
test('proxy session bearer, sanitized fields, validation, status and connection failures',async()=>{let session={accessToken:'spring-token'};let captured;let status=204;let fail=false;const proxy=load('lib/calendar-proxy.ts',{'next/server':{NextResponse:{json:(v,o)=>new Response(JSON.stringify(v),o)}},'next-auth':{getServerSession:async()=>session},'@/lib/next-auth':{authOptions:{}},'@/lib/calendar-api':api},{fetch:async(url,opts)=>{captured={url,opts};if(fail)throw Error('private configuration');return new Response(status===204?null:JSON.stringify({message:'backend validation'}),{status});}}).proxyCalendar;const req=(method,path,body)=>({method,url:'http://localhost/api/calendar/entries'+path,json:async()=>body});assert.equal((await proxy(req('DELETE','/42?version=0'),'42')).status,204);assert.equal(captured.opts.headers.Authorization,'Bearer spring-token');assert.match(captured.url,/version=0/);assert.equal((await proxy(req('DELETE','/42'),'42')).status,400);assert.equal((await proxy(req('GET','?from=2026-02-30&to=2026-10-31'))).status,400);status=400;const response=await proxy(req('PUT','/42',{...entry,shopId:99}),'42');assert.equal(response.status,400);assert.equal((await response.json()).message,'backend validation');assert.equal(JSON.parse(captured.opts.body).shopId,undefined);assert.equal(JSON.parse(captured.opts.body).id,undefined);fail=true;assert.equal((await proxy(req('GET','/42'),'42')).status,502);session=null;assert.equal((await proxy(req('GET','/42'),'42')).status,401);});
test('aborted request remains aborted',async()=>{const c=new AbortController();c.abort();const client=load('lib/calendar-api.ts',{}, {fetch:async()=>{throw Error('abort');}});await assert.rejects(client.calendarRequest('',{signal:c.signal}),/abort/);});
function pageHarness(){
  let slots=[],index=0,effects=[],session={user:{id:'owner',shopId:1},accessToken:'backend'},status='authenticated',requests=[];
  const same=(a,b)=>a&&b&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i]));
  const react={useState(initial){const i=index++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return [slots[i],value=>slots[i]=typeof value==='function'?value(slots[i]):value];},useRef(initial){const i=index++;return slots[i]??(slots[i]={current:initial});},useMemo(fn,deps){const i=index++;if(!slots[i]||!same(slots[i].deps,deps))slots[i]={deps,value:fn()};return slots[i].value;},useEffect(fn,deps){const i=index++;if(!slots[i]||!same(slots[i].deps,deps)){effects.push(()=>{slots[i]?.cleanup?.();slots[i]={deps,cleanup:fn()};});}}};
  const jsx=(type,props)=>({type,props:props||{}});
  const fakeRequest=(path='',options={})=>new Promise((resolve,reject)=>requests.push({path,options,resolve,reject}));
  const imports={'react':react,'react/jsx-runtime':{jsx,jsxs:jsx,Fragment:'Fragment'},'next-auth/react':{useSession:()=>({data:session,status})},'@/lib/calendar-api':{...api,calendarRequest:fakeRequest},'@/components/currency-provider':{useCurrency:()=>({formatSharedMoney:String})},'@/components/shop-timezone-provider':{useShopTimezone:()=> 'UTC'},'@/lib/date-time':{getShopTimezone:()=> 'UTC',parseTimestamp:v=>new Date(v)}};
  for(const name of ['@/components/ui/popover','@/components/ui/alert-dialog','lucide-react'])imports[name]=new Proxy({},{get:(_,key)=>String(key)});
  const exports={};const code=ts.transpileModule(fs.readFileSync('app/dashboard/calendar/page.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText;
  vm.runInNewContext(code,{exports,require:n=>imports[n],Error,Intl,Date,Set,Uint8Array,TextDecoder,atob,AbortController,window:{setInterval:()=>0,clearInterval(){},setTimeout:()=>0,clearTimeout(){},addEventListener(){},removeEventListener(){}},setTimeout,clearTimeout});
  let tree;
  const render=()=>{index=0;tree=exports.default();const pending=effects;effects=[];pending.forEach(fn=>fn());return tree;};
  const nodes=()=>{const result=[];const walk=v=>{if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object'&&v.props){result.push(v);walk(v.props.children);}};walk(tree);return result;};
  const text=v=>Array.isArray(v)?v.map(text).join(''):v&&typeof v==='object'?text(v.props?.children):typeof v==='string'?v:'';
  const find=label=>nodes().find(n=>n.type==='button'&&text(n.props.children).includes(label));
  const editor=()=>nodes().find(n=>typeof n.type==='function'&&n.type.name==='EntryEditor');
  return {render,nodes,find,editor,requests,setAccount(value){session=value;},get tree(){return tree;}};
}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
test('page month range, failed save preservation, duplicate prevention, conflict review, account masking and stale responses',async()=>{
  const h=pageHarness();h.render();h.render();const initial=h.requests[0];const params=new URLSearchParams(initial.path.slice(1));const from=params.get('from'),to=params.get('to');assert.equal((Date.parse(to)-Date.parse(from))/86400000,41);assert.equal(new Date(from+'T00:00:00Z').getUTCDay(),1);
  initial.resolve([]);await tick();h.render();h.find('Add entry').props.onClick();h.render();let ed=h.editor();ed.props.onChange({...ed.props.draft,title:'Unsaved delivery'});h.render();ed=h.editor();ed.props.onSave();ed.props.onSave();assert.equal(h.requests.filter(r=>r.options.method==='POST').length,1);h.requests.at(-1).reject(new api.CalendarApiError('validation detail',400));await tick();h.render();assert.equal(h.editor().props.draft.title,'Unsaved delivery');assert.match(h.editor().props.error,/validation detail/);
  h.editor().props.onSave();h.requests.at(-1).resolve(api.decodeEntry(entry));await tick();h.render();assert.equal(h.editor(),undefined);const refreshed=h.requests.at(-1);refreshed.resolve([api.decodeEntry(entry)]);await tick();h.render();const calendarButton=h.nodes().find(n=>n.type==='button'&&n.props.title?.startsWith('Delivery'));calendarButton.props.onClick();h.render();ed=h.editor();ed.props.onChange({...ed.props.draft,title:'My change'});h.render();h.editor().props.onSave();assert.equal(JSON.parse(h.requests.at(-1).options.body).version,0);h.requests.at(-1).reject(new api.CalendarApiError('changed',409));await tick();h.render();assert.equal(h.editor(),undefined);h.find('Load latest entry').props.onClick();h.requests.at(-1).resolve(api.decodeEntry({...entry,title:'Other change',version:1}));await tick();h.render();h.find('Reviewed').props.onClick();h.render();assert.equal(h.editor().props.draft.title,'My change');assert.equal(h.editor().props.draft.version,1);assert.equal(h.requests.filter(r=>r.options.method==='PUT').length,1);
  h.editor().props.onSave();const staleSave=h.requests.at(-1);h.setAccount({user:{id:'other',shopId:2},accessToken:'other-backend'});h.render();assert.equal(h.editor(),undefined);h.render();const otherLoad=h.requests.at(-1);otherLoad.resolve([]);staleSave.resolve(api.decodeEntry({...entry,title:'My change',version:2}));await tick();h.render();assert.equal(h.nodes().some(n=>n.props.title?.startsWith('My change')),false);
  h.find('Next period')?.props.onClick?.();
});
test('page complete/reopen and versioned delete use persisted server state',async()=>{
 const h=pageHarness();h.render();h.render();h.requests[0].resolve([api.decodeEntry(entry)]);await tick();h.render();const open=()=>h.nodes().find(n=>n.type==='button'&&n.props.title?.startsWith('Delivery')).props.onClick();
 open();h.render();let editor=h.editor();editor.props.onChange({...editor.props.draft,completed:true});h.render();h.editor().props.onSave();assert.equal(JSON.parse(h.requests.at(-1).options.body).completed,true);h.requests.at(-1).resolve(api.decodeEntry({...entry,completed:true,version:1}));await tick();h.render();h.requests.at(-1).resolve([api.decodeEntry({...entry,completed:true,version:1})]);await tick();h.render();open();h.render();editor=h.editor();assert.equal(editor.props.draft.version,1);editor.props.onChange({...editor.props.draft,completed:false});h.render();h.editor().props.onSave();assert.equal(JSON.parse(h.requests.at(-1).options.body).version,1);h.requests.at(-1).resolve(api.decodeEntry({...entry,version:2}));await tick();h.render();h.requests.at(-1).resolve([api.decodeEntry({...entry,version:2})]);await tick();h.render();open();h.render();h.editor().props.onDelete();h.render();h.find('Delete entry').props.onClick();assert.equal(h.requests.at(-1).path,'/42?version=2');assert.equal(h.requests.at(-1).options.method,'DELETE');h.requests.at(-1).resolve(null);await tick();h.render();assert.equal(h.editor(),undefined);
});
test('period changes abort and ignore old range responses; week loads seven days',async()=>{
 const h=pageHarness();h.render();h.render();const old=h.requests[0];const next=h.nodes().find(n=>n.props['aria-label']==='Next period');next.props.onClick();h.render();assert.equal(old.options.signal.aborted,true);const current=h.requests.at(-1);current.resolve([]);old.resolve([api.decodeEntry(entry)]);await tick();h.render();assert.equal(h.nodes().some(n=>n.props.title?.startsWith('Delivery')),false);h.find('week').props.onClick();h.render();const query=new URLSearchParams(h.requests.at(-1).path.slice(1));assert.equal((Date.parse(query.get('to'))-Date.parse(query.get('from')))/86400000,6);
});
test('sales popover waits five seconds for mouse and opens immediately for touch/click',()=>{
 const source=fs.readFileSync('app/dashboard/calendar/page.tsx','utf8');const snippet=source.slice(source.indexOf('function SalesDatePopover('),source.indexOf('function DaySalesSummary('));let slots=[],i=0,timers=new Map(),serial=0,previews=0,selections=0;
 const exports={};const jsx=(type,props)=>({type,props});const context={exports,require:()=>({jsx,jsxs:jsx}),Date,Popover:'Popover',PopoverAnchor:'Anchor',PopoverTrigger:'Trigger',PopoverContent:'Content',ReceiptText:'Receipt',X:'X',useState(initial){const n=i++;if(!(n in slots))slots[n]=initial;return [slots[n],v=>slots[n]=typeof v==='function'?v(slots[n]):v];},useRef(initial){const n=i++;return slots[n]??(slots[n]={current:initial});},useEffect(){},setTimeout(fn,delay){timers.set(++serial,{fn,delay});return serial;},clearTimeout(id){timers.delete(id);}};
 vm.runInNewContext(ts.transpileModule(snippet+'\nexports.component=SalesDatePopover;',{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,context);
 const render=()=>{i=0;return exports.component({onPreview:()=>previews++,onSelect:()=>selections++,children:null});};let tree=render();let cell=tree.props.children[0].props.children;cell.props.onPointerEnter({pointerType:'mouse'});assert.equal(render().props.open,false);assert.equal([...timers.values()][0].delay,5000);[...timers.values()][0].fn();tree=render();assert.equal(tree.props.open,true);tree.props.onOpenChange(false);tree=render();cell=tree.props.children[0].props.children;cell.props.onPointerDown({pointerType:'touch'});cell.props.onClick({target:{closest:()=>null}});assert.equal(render().props.open,true);assert.equal(selections,1);assert.ok(previews>=2);
});
